apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <NFS_SERVER_IP>   # Replace with your K3s server IP
    path: /srv/nfs/k3s-share
  persistentVolumeReclaimPolicy: Retain
