apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.139.130
    path: /srv/nfs/k3s-share
  persistentVolumeReclaimPolicy: Retain
